### ISSUE TITLE
CAO Tools - installation error on one machine but not another.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#157]
In Bforartists 0.9.6 I tried installing the addon COA tools, in one machine it worked fine, in another no. 

Just wondering, why would one side work and the other not? What are these referring to? We are both installing the same addon to the same BFA version even with nearly identical addons. 

What is the trouble shooting process? Should I disactivate all addons then try install? Reset to factory? Test another template? 

I've included the error below: 

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Bforartists 096\2.79\scripts\modules\addon_utils.py", line 338, in enable
    mod = __import__(module_name)
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\coa_tools\__init__.py", line 45, in <module>
    modules = developer_utils.setup_addon_modules(__path__, __name__)
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\coa_tools\developer_utils.py", line 57, in setup_addon_modules
    modules = import_submodules(names)
  File "C:\Users\draiss\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\coa_tools\developer_utils.py", line 49, in import_submodules
    modules.append(importlib.import_module("." + name, package_name))
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\coa_tools\addon_updater.py", line 27, in <module>
    import urllib.request
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\email\_policybase.py", line 7, in <module>
    from email import header
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\email\header.py", line 16, in <module>
    import email.quoprimime
  File "C:\Program Files (x86)\Bforartists 096\2.79\python\lib\email\quoprimime.py", line 44, in <module>
    from string import ascii_letters, digits, hexdigits
ImportError: cannot import name 'ascii_letters'
```

**Comment by ReinerBforartists** [comment]
Phew, i have no idea what goes wrong here. It can be everything in the addon. 

It's definitely nothing that we could fix. You should contact the addon author here.
