### ISSUE TITLE
3.1.3 on Windows 10 fails to launch

### ISSUE THREAD

**Issue by jamesncl** [Bforartists/Bforartists#2961]
On Windows 10 64 bit:

Edition	Windows 10 Home
Version	21H2
Installed on	‎10/‎05/‎2021
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

I did a clean install using the windows installer for version 3.1.3, then on trying to launch the program I see a command window, then a grey window, which disappears after a second or two. Same problem using the zip folder version. When running from cmd I get this error:

```
C:\Program Files\Bforartists 3\3.1.3>bforartists.exe
Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.1.3\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Bforartists 3\3.1.3\3.2\scripts\addons\materials_library_vx\__init__.py", line 42, in <module>
    os.mkdir(matlib_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\jdall\\AppData\\Roaming\\Bforartists\\Bforartists\\matlib'
ERROR (gpu.shader): overlay_armature_sphere_solid VertShader:
      |
   12 | #define GPU_ARB_texture_cube_map_array
      |                                                      ^
      | Error: '' : illegal recursive expansion of macro pixelFac
      | Error: 'pixelFac' : failed to expand macro

ERROR (gpu.shader): overlay_armature_sphere_solid FragShader:
      |
   12 | #define GPU_ARB_texture_cube_map_array
      |                                                      ^
      | Error: '' : illegal recursive expansion of macro pixelFac
      | Error: 'pixelFac' : failed to expand macro

Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF747B81BF0
Module  : bforartists.exe
Thread  : 00002a38
Writing: C:\Users\jdall\AppData\Local\Temp\blender.crash.txt
```

I have no directory called `Bforartists` in my `AppData\Roaming` directory, so I guess it's looking in the wrong place for `matlib`? Or is there some other dependency program I need to install?

**Comment by ReinerBforartists** [comment]
Hi jamesncl,

Thanks for the report. You have two problems here. None of it has to do with the installer. The zip file should show them too.

> I have no directory called Bforartists in my AppData\Roaming directory, so I guess either the installer has not installed files in the correct place, or it's looking in the wrong place for matlib?

Neither nor. This warning is normal. Click in the Splash screen at the Next button. This installs the Bforartists folder in the appdata\roaming directory. But the warning is harmless. It's just that the addon doesn't show then.

```
ERROR (gpu.shader): overlay_armature_sphere_solid VertShader:
      |
   12 | #define GPU_ARB_texture_cube_map_array
      |                                                      ^
      | Error: '' : illegal recursive expansion of macro pixelFac
      | Error: 'pixelFac' : failed to expand macro

ERROR (gpu.shader): overlay_armature_sphere_solid FragShader:
      |
   12 | #define GPU_ARB_texture_cube_map_array
      |                                                      ^
      | Error: '' : illegal recursive expansion of macro pixelFac
      | Error: 'pixelFac' : failed to expand macro

Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF747B81BF0
Module  : bforartists.exe
Thread  : 00002a38
Writing: C:\Users\jdall\AppData\Local\Temp\blender.crash.txt
```

This is something different. And i have unfortunately no idea what is going on there. It might be a problem with your graphics card. I have updated the Cuda version to the latest by Blender required version with the newest release. My problem with such errors is, there is little that i can do. We rely at the Blender code here :/

Maybe you can reproduce it with Blender. Then you could report it to Blender.

**Comment by jamesncl** [comment]
Ah okay, thanks for the reply - yes I'm using a rather old laptop, and I just checked using GPU-Z - graphics card doesn't support CUDA. So I guess that's the problem. About to reproduce with standard Blender...

**Comment by jamesncl** [comment]
I've just installed the latest Blender 3.1.2 and I can launch it, and do editing. So I guess it might not be a Blender problem after all. I'm using an HP Envy Notebook, it's about 8-10 years old, 8GB RAM, i5 1.8 GHz. It wasn't meant to be a gaming or graphics machine so the GPU is quite poor, here's what GPU-Z says:

![image](https://user-images.githubusercontent.com/15979056/162993445-ad2841ec-4526-4b2b-a123-f7d2d440e303.png)

Here's what `blender.crash` says, not sure it's very helpful:

```
# Blender 3.2.0, Commit date: 2022-04-09 15:51, Hash 9f2f83236391

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF724E51BF0
Exception Module      : bforartists.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000008


Stack trace:
bforartists.exe     :0x00007FF724AB8040  PyInit_manta_main
bforartists.exe     :0x00007FF7201A4616  Symbols not available


Loaded Modules :
0x00007FF71F680000 3.1.3.0              bforartists.exe  
0x00007FF909670000 10.0.19041.1566      ntdll.dll  
0x00007FF908E80000 10.0.19041.1566      KERNEL32.DLL  
0x00007FF906E20000 10.0.19041.1566      KERNELBASE.dll  
0x00007FF907770000 10.0.19041.546       WS2_32.dll  
0x00007FF9087B0000 10.0.19041.1466      RPCRT4.dll  
0x00007FF900490000                      tbbmalloc.dll  
0x00007FF8FA020000                      tbb.dll  
0x00007FF908120000 10.0.19041.1503      USER32.dll  
0x00007FF9076C0000 10.0.19041.1586      win32u.dll  
0x00007FF9077E0000 10.0.19041.1202      GDI32.dll  
0x00007FF907320000 10.0.19041.1566      gdi32full.dll  
0x00007FF907180000 10.0.19041.789       msvcp_win.dll  
0x00007FF9075C0000 10.0.19041.789       ucrtbase.dll  
0x00007FF908F40000 10.0.19041.1466      ADVAPI32.dll  
0x00007FF8F9F90000 14.29.30139.0        MSVCP140.dll  
0x00007FF909320000 7.0.19041.546        msvcrt.dll  
0x00007FF9093E0000 10.0.19041.1586      sechost.dll  
0x00007FF907910000 10.0.19041.1566      SHELL32.dll  
0x00007FF902070000 14.29.30139.0        VCRUNTIME140_1.dll  
0x00007FF908E70000 10.0.19041.546       PSAPI.DLL  
0x00007FF9080C0000 10.0.19041.1023      SHLWAPI.dll  
0x00007FF8EF980000 10.0.19041.867       dbghelp.dll  
0x00007FF907220000 10.0.19041.1151      CFGMGR32.dll  
0x00007FF8C2A80000 8.0.1.0              openvdb.dll  
0x00007FF8F86E0000 10.0.19041.1566      OPENGL32.dll  
0x00007FF909180000 10.0.19041.1202      ole32.dll  
0x00007FF902090000 14.29.30139.0        VCRUNTIME140.dll  
0x00007FF9082C0000 10.0.19041.1566      combase.dll  
0x00007FF908FF0000 10.0.19041.1566      shcore.dll  
0x00007FF9078E0000 10.0.19041.546       IMM32.dll  
0x00007FF8C1D20000 58.76.100.0          avformat-58.dll  
0x00007FF900470000 58.13.100.0          avdevice-58.dll  
0x00007FF907810000 10.0.19041.985       OLEAUT32.dll  
0x00007FF8C1A50000 56.70.100.0          avutil-56.dll  
0x00007FF907590000 10.0.19041.1023      bcrypt.dll  
0x00007FF8F2440000 5.9.100.0            swscale-5.dll  
0x0000000070440000 1.0.28.0             libsndfile-1.dll  
0x00007FF8C25B0000 3.10.2150.1013       python310.dll  
0x00007FF8C93F0000 1.20.1.0             OpenAL32.dll  
0x00007FF8C3970000 2.0.12.0             SDL2.dll  
0x000000006ACC0000                      libgmp-10.dll  
0x00007FF908A00000 10.0.19041.1566      SETUPAPI.dll  
0x00007FF902050000                      libgmpxx.dll  
0x00007FF900DB0000                      tbbmalloc_proxy.dll  
0x00007FF8F4B90000 6.10.19041.1110      COMCTL32.dll  
0x00007FF8F6540000 10.0.19041.1         AVIFIL32.dll  
0x00007FF8F5920000 10.0.19041.546       VERSION.dll  
0x00007FF8FA080000 10.0.19041.1566      GLU32.dll  
0x0000000070680000                      libfftw3-3.dll  
0x00007FF8F81D0000 10.0.19041.546       Secur32.dll  
0x00007FF8F9770000 10.0.19041.1         AVICAP32.dll  
0x00007FF8F6CA0000 10.0.19041.546       WINMM.dll  
0x00007FF8F42B0000 10.0.19041.1         MSVFW32.dll  
0x00007FF8ECFC0000 10.0.19041.1         MSACM32.dll  
0x00007FF8EA6B0000 10.0.19041.1         winmmbase.dll  
0x00007FF8A3310000 58.134.100.0         avcodec-58.dll  
0x00007FF8F4280000 3.9.100.0            swresample-3.dll  
0x00007FF906D10000 10.0.19041.1586      SSPICLI.DLL  
0x00007FF904D30000 10.0.19041.546       kernel.appcore.dll  
0x00007FF904F30000 10.0.19041.1566      windows.storage.dll  
0x00007FF9067B0000 10.0.19041.1566      Wldp.dll  
0x00007FF904850000 10.0.19041.1266      uxtheme.dll  
0x00007FF9070F0000 10.0.19041.1415      bcryptPrimitives.dll  
0x00007FF906D60000 10.0.19041.844       profapi.dll  
0x00007FF908620000 2001.12.10941.16384  clbcatq.dll  
0x00007FF8FCA20000 10.0.19041.1503      MMDevApi.dll  
0x00007FF906AF0000 10.0.19041.1566      DEVOBJ.dll  
0x00007FF8E9700000 10.0.19041.1566      AUDIOSES.DLL  
0x00007FF906C90000 10.0.19041.546       powrprof.dll  
0x00007FF906C70000                      UMPDC.dll  
0x00007FF9088E0000 10.0.19041.1566      MSCTF.dll  
0x00007FF8FFC30000 10.0.19041.1566      AppXDeploymentClient.dll  
0x00007FF8A7770000 21.20.16.4627        ig9icd64.dll  
0x00007FF902B30000 10.0.19041.546       WTSAPI32.dll  
0x00007FF904A40000 10.0.19041.746       dwmapi.dll  
0x00007FF8FE3A0000 10.0.19041.546       dxcore.dll  
0x00007FF8FB6A0000 21.20.16.4627        igc64.dll  
0x00007FF905730000 10.0.19041.1566      dxgi.dll  
0x00007FF903330000 10.0.19041.1202      d3d11.dll  
0x00007FF8FCAB0000 21.20.16.4627        igd10iumd64.dll  
0x00007FF906820000 10.0.19041.662       ncrypt.dll  
0x00007FF9067E0000 10.0.19041.546       NTASN1.dll  
0x00007FF8F48E0000 10.0.19041.1387      dataexchange.dll  
0x00007FF903B60000 10.0.19041.1566      dcomp.dll  
0x00007FF901300000 10.0.19041.964       twinapi.appcore.dll  
0x00007FF8F8A70000 10.0.19041.1566      textinputframework.dll  
0x00007FF903D50000 10.0.19041.546       CoreUIComponents.dll  
0x00007FF904430000 10.0.19041.746       CoreMessaging.dll  
0x00007FF905B20000 10.0.19041.546       ntmarta.dll  
0x00007FF902D70000 10.0.19041.1348      wintypes.dll  
0x00007FF8E5CD0000 10.0.19041.1023      explorerframe.dll  
0x00007FF906700000 10.0.19041.546       CRYPTSP.dll  
0x00007FF905E90000 10.0.19041.1052      rsaenh.dll  
0x00007FF906720000 10.0.19041.546       CRYPTBASE.dll  
0x000001DBE94C0000 3.10.2150.1013       python3.DLL  
0x00007FF8F26E0000 3.10.2150.1013       _bz2.pyd  
0x00007FF8ED9B0000 3.10.2150.1013       _lzma.pyd  

# Python backtrace

```

**Comment by ReinerBforartists** [comment]
Thanks for investigating. I am as curious as you why Blender works, and Bforartists not. But the error message doesn't really give me a hint here. I would need to debug it. And for this i would be able to reproduce the problem. But here it works just fine. 

It can be that there is a little change between the official Blender release version 3.1.2 and the current development version 3.2, which is based at the master. We rely at the master branch of Blender, we are always one step ahead to the Blender release versions.

So as a last idea, could you please have a look if the newest Blender developer version of Blender still works for you. They are located here. Download the 3.20 alpha version. This version is similar to our Bforartists version 3.1.3 : https://builder.blender.org/download/daily/

But no matter if it fails or works, ten years is really old. I think you can be happy that at least the current Blender version launches. And i don't think that you will get support for it in case this Blender developer version crashes for you too. Sometimes it is simply time to let go. 3D is very hardware hungry.

As told, there is little that we can do at our end. We rely at the Blender code. We just change the UI. We usually don't touch any relevant code besides that. It can always be that we introduce a bug while the merge of the Blender code. But then it should be reproduceable. And here it is not, unfortunately.

**Comment by ReinerBforartists** [comment]
Let's close this issue. There is unfortunately nothing we can do.
