### ISSUE TITLE
Bforartists keymaps error after latest merge (6/13/2023) 

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3584]
Getting this issue with the latest merge with our keymaps.

```
Traceback (most recent call last):
  File "/home/juso3d/Documents/Blender-Dev/build_linux_full/bin/4.0/scripts/modules/bpy/utils/__init__.py", line 676, in keyconfig_set
    execfile(filepath)
  File "/home/juso3d/Documents/Blender-Dev/build_linux_full/bin/4.0/scripts/modules/bpy/utils/__init__.py", line 104, in execfile
    mod_spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/juso3d/Documents/Blender-Dev/build_linux_full/bin/4.0/scripts/presets/keyconfig/bforartists.py", line 8122, in <module>
    keyconfig_import_from_data(
  File "/home/juso3d/Documents/Blender-Dev/build_linux_full/bin/4.0/scripts/modules/bl_keymap_utils/io.py", line 288, in keyconfig_import_from_data
    keyconfig_init_from_data(kc, keyconfig_data)
  File "/home/juso3d/Documents/Blender-Dev/build_linux_full/bin/4.0/scripts/modules/bl_keymap_utils/io.py", line 274, in keyconfig_init_from_data
    keymap_init_from_data(km, km_items, is_modal=km_args.get("modal", False))
  File "/home/juso3d/Documents/Blender-Dev/build_linux_full/bin/4.0/scripts/modules/bl_keymap_utils/io.py", line 249, in keymap_init_from_data
    for (kmi_idname, kmi_args, kmi_data) in km_items:
ValueError: too many values to unpack (expected 3)


```

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/797206a3-6895-489a-a0fc-5a9600cee72e)

Can confirm. This may be an issue with their  with their  with their A with their API updates they are doing with Blender 4.0.0 which is.. not great.

**Comment by Draise14** [comment]
Got a clue. Saving a custom map from Blender then overwriting the body with Bforartists keymap then compiling that new one in... fixed it.

**Comment by ReinerBforartists** [comment]
I thought this one was fixed? Did a fetch and a pull and then built the devbuild versions ...

![stilltroubled](https://github.com/Bforartists/Bforartists/assets/13919702/69fe2628-8075-43ff-a5c2-39104b6546ad)

**Comment by ReinerBforartists** [comment]
Odd. Whatever hiccup this was, doing a second fetch and pull healed it.

**Comment by Draise14** [comment]
I commit this fix a couple days ago. It was a versioning error in the keymap.

**Comment by ReinerBforartists** [comment]
Yes, i noticed. But something went wrong with pulling here. Did not arrive with the first try. Odd Github was odd ^^
