### ISSUE TITLE
space_toolbar.py  - uv mirror/rotate operators - context overrides needs updating. 

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3999]
Notice some of the toolbar uv operators are using the old context override, which no longer work.

```
Python: Traceback (most recent call last):
  File "/home/juso3d/Git/Blender-Git/bfa_build_linux/bin/4.1/scripts/startup/bl_ui/space_toolbar.py", line 1119, in execute
    bpy.ops.transform.mirror(override, constraint_axis=(True, False, False))
  File "/home/juso3d/Git/Blender-Git/bfa_build_linux/bin/4.1/scripts/modules/bpy/ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "/home/juso3d/Git/Blender-Git/bfa_build_linux/bin/4.1/scripts/modules/bpy/ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

```

![image](https://github.com/Bforartists/Bforartists/assets/25260650/5544a169-ef8a-4ffe-9052-689eaeef0015)

**Comment by ReinerBforartists** [comment]
Toolbar is oooold ^^
