### ISSUE TITLE
Bforartists 0.9.6 - go through the addons again

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#69]
The FBX export bug showed that we have again a discrepance between the Blender addons and the Bforartists addons in version 0.9.6. And again it's quite a few, as meld shows. 

So we need to go through them again, one by one.

**Comment by Draise14** [comment]
I found that bug. Here is the code I found and after my deadlines I'll upload the sample scene (of which works fine in Blender 2.79a): 

`
Traceback (most recent call last):
  File "G:\3D stuff\Bforartists\BFA 0.9.6 - 64bit - 2.79a\2.79\scripts\addons\io_scene_fbx\__init__.py", line 620, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "G:\3D stuff\Bforartists\BFA 0.9.6 - 64bit - 2.79a\2.79\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3087, in save
    ret = save_single(operator, context.scene, filepath, **kwargs_mod)
  File "G:\3D stuff\Bforartists\BFA 0.9.6 - 64bit - 2.79a\2.79\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2994, in save_single
    fbx_objects_elements(root, scene_data)
  File "G:\3D stuff\Bforartists\BFA 0.9.6 - 64bit - 2.79a\2.79\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2793, in fbx_objects_elements
    fbx_data_mesh_elements(objects, me_obj, scene_data, done_meshes)
  File "G:\3D stuff\Bforartists\BFA 0.9.6 - 64bit - 2.79a\2.79\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 1069, in fbx_data_mesh_elements
    collayer.data.foreach_get("color", t_lc)
RuntimeError: internal error setting the array

location: <unknown location>:-1
`

**Comment by ReinerBforartists** [comment]
Hey Draise, 
The FBX bug is already fixed here: https://github.com/Bforartists/Bforartists/issues/63
It was the reason why i stumbled across the differences in the addons again. And so i made this task. Seems that something went wrong with pulling the newest addons at one point.

**Comment by ReinerBforartists** [comment]
Fixed in master
https://github.com/Bforartists/Bforartists/commit/3eeeb5d3719eeed45cf979e67d9ca5286c4a0073
